import * as Types from './types/types.generated';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type ApneaSessionFragment = { __typename?: 'ApneaSession', id: any, sessionName?: string | null, startTime: any, endTime: any };

export type DiveFragment = { __typename?: 'Dive', id: any, depth?: number | null, disciplineType?: string | null, distance?: number | null, diveName?: string | null, diveTime?: number | null, updatedAt: any };

export type ApneaSessionWithDivesFragment = { __typename?: 'ApneaSession', id: any, sessionName?: string | null, startTime: any, endTime: any, dives: Array<{ __typename?: 'Dive', id: any, depth?: number | null, disciplineType?: string | null, distance?: number | null, diveName?: string | null, diveTime?: number | null, updatedAt: any }> };

export type MyApneaSessionConnectionFragment = { __typename?: 'ApneaSessionConnection', nodes: Array<{ __typename?: 'ApneaSession', id: any, sessionName?: string | null, startTime: any, endTime: any, dives: Array<{ __typename?: 'Dive', id: any, depth?: number | null, disciplineType?: string | null, distance?: number | null, diveName?: string | null, diveTime?: number | null, updatedAt: any }> }> };

export type InsertPrepopulatedApneaSessionMutationVariables = Types.Exact<{ [key: string]: never; }>;


export type InsertPrepopulatedApneaSessionMutation = { __typename?: 'Mutation', insertApneaSession: { __typename?: 'ApneaSession', id: any, sessionName?: string | null, startTime: any, endTime: any, dives: Array<{ __typename?: 'Dive', id: any, depth?: number | null, disciplineType?: string | null, distance?: number | null, diveName?: string | null, diveTime?: number | null, updatedAt: any }> } };

export type ApneaSessionsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type ApneaSessionsQuery = { __typename?: 'Query', apneaSessions: { __typename?: 'ApneaSessionConnection', nodes: Array<{ __typename?: 'ApneaSession', id: any, sessionName?: string | null, startTime: any, endTime: any, dives: Array<{ __typename?: 'Dive', id: any, depth?: number | null, disciplineType?: string | null, distance?: number | null, diveName?: string | null, diveTime?: number | null, updatedAt: any }> }> } };


export const InsertPrepopulatedApneaSessionDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"insertPrepopulatedApneaSession"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"insertApneaSession"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"apneaSessionInput"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"startTime"},"value":{"kind":"StringValue","value":"2015-07-01T08:59:60.123","block":false}},{"kind":"ObjectField","name":{"kind":"Name","value":"endTime"},"value":{"kind":"StringValue","value":"2015-07-01T08:59:60.123","block":false}},{"kind":"ObjectField","name":{"kind":"Name","value":"sessionName"},"value":{"kind":"StringValue","value":"oog","block":false}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"ApneaSessionWithDives"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ApneaSession"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ApneaSession"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"sessionName"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"Dive"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Dive"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"depth"}},{"kind":"Field","name":{"kind":"Name","value":"disciplineType"}},{"kind":"Field","name":{"kind":"Name","value":"distance"}},{"kind":"Field","name":{"kind":"Name","value":"diveName"}},{"kind":"Field","name":{"kind":"Name","value":"diveTime"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ApneaSessionWithDives"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ApneaSession"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"ApneaSession"}},{"kind":"Field","name":{"kind":"Name","value":"dives"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"Dive"}}]}}]}}]} as unknown as DocumentNode<InsertPrepopulatedApneaSessionMutation, InsertPrepopulatedApneaSessionMutationVariables>;
export const ApneaSessionsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"ApneaSessions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"apneaSessions"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"queryParams"},"value":{"kind":"ObjectValue","fields":[]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"MyApneaSessionConnection"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ApneaSession"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ApneaSession"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"sessionName"}},{"kind":"Field","name":{"kind":"Name","value":"startTime"}},{"kind":"Field","name":{"kind":"Name","value":"endTime"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"Dive"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Dive"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"depth"}},{"kind":"Field","name":{"kind":"Name","value":"disciplineType"}},{"kind":"Field","name":{"kind":"Name","value":"distance"}},{"kind":"Field","name":{"kind":"Name","value":"diveName"}},{"kind":"Field","name":{"kind":"Name","value":"diveTime"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ApneaSessionWithDives"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ApneaSession"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"ApneaSession"}},{"kind":"Field","name":{"kind":"Name","value":"dives"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"Dive"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"MyApneaSessionConnection"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ApneaSessionConnection"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodes"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"ApneaSessionWithDives"}}]}}]}}]} as unknown as DocumentNode<ApneaSessionsQuery, ApneaSessionsQueryVariables>;