import * as Types from './types/types.generated';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type DeepDiveReportFieldsV1Fragment = { __typename?: 'DeepDiveReportFieldsV1', isActive?: boolean | null, fieldOrder?: number | null, discipline?: { __typename?: 'DeepDisciplineV1', discipline?: Types.DisciplinesEnumV1 | null, isActive?: boolean | null, fieldOrder?: number | null } | null, goalDepth?: { __typename?: 'DeepGoalDepthV1', depth?: number | null, isActive?: boolean | null, fieldOrder?: number | null } | null, achievedDepth?: { __typename?: 'DeepAchievedDepthV1', depth?: number | null, isActive?: boolean | null, fieldOrder?: number | null } | null };

export type DynamicReportFieldsV1Fragment = { __typename?: 'DynamicReportFieldsV1', isActive?: boolean | null, fieldOrder?: number | null, discipline?: { __typename?: 'DynDisciplineV1', discipline?: Types.DisciplinesEnumV1 | null, isActive?: boolean | null, fieldOrder?: number | null } | null, goalDistance?: { __typename?: 'DynGoalDistanceV1', distance?: number | null, isActive?: boolean | null, fieldOrder?: number | null } | null, achievedDistance?: { __typename?: 'DynAchievedDistanceV1', distance?: number | null, isActive?: boolean | null, fieldOrder?: number | null } | null };

export type StaticReportFieldsV1Fragment = { __typename?: 'StaticReportFieldsV1', isActive?: boolean | null, fieldOrder?: number | null, timeGoal?: { __typename?: 'StaticTimeGoalV1', time?: any | null, isActive?: boolean | null, fieldOrder?: number | null } | null, timeAchieved?: { __typename?: 'StaticTimeAchievedV1', time?: any | null, isActive?: boolean | null, fieldOrder?: number | null } | null };

export const DeepDiveReportFieldsV1FragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"DeepDiveReportFieldsV1"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"DeepDiveReportFieldsV1"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"discipline"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"discipline"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}},{"kind":"Field","name":{"kind":"Name","value":"goalDepth"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"depth"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}},{"kind":"Field","name":{"kind":"Name","value":"achievedDepth"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"depth"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}}]} as unknown as DocumentNode<DeepDiveReportFieldsV1Fragment, unknown>;
export const DynamicReportFieldsV1FragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"DynamicReportFieldsV1"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"DynamicReportFieldsV1"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"discipline"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"discipline"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}},{"kind":"Field","name":{"kind":"Name","value":"goalDistance"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"distance"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}},{"kind":"Field","name":{"kind":"Name","value":"achievedDistance"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"distance"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}}]} as unknown as DocumentNode<DynamicReportFieldsV1Fragment, unknown>;
export const StaticReportFieldsV1FragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StaticReportFieldsV1"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"StaticReportFieldsV1"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"timeGoal"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"time"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}},{"kind":"Field","name":{"kind":"Name","value":"timeAchieved"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"time"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"fieldOrder"}}]}}]} as unknown as DocumentNode<StaticReportFieldsV1Fragment, unknown>;